package bootstrap

import (
	"crypto/rand"
	"encoding/hex"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"routebox/backend/internal/users"
)

// naiveUsersFile is the name of the generated credential list, next to the
// Caddyfile that imports it. One name, so the planner, the bootstrap and the
// post-apply sync cannot point at three different files.
const naiveUsersFile = "naive-users.caddy"

// NaiveUser is one credential pair dest checks a naive client against. It is not
// a second user model: every one of these is derived from an inbound user, which
// is what the panel writes.
type NaiveUser struct {
	Name     string
	Password string
}

// NaiveUsersPath is where the generated credential list lives, given the
// Caddyfile that imports it.
func NaiveUsersPath(caddyfile string) string {
	return filepath.Join(filepath.Dir(caddyfile), naiveUsersFile)
}

// naivePasswordProtocols are the inbound types whose credential is a password,
// in the order a user's naive password is taken from them. vless is absent on
// purpose: its credential is a uuid, and handing it to basic_auth would invent a
// naive account nobody granted.
var naivePasswordProtocols = []string{"trojan", "mieru", "hysteria2"}

// NaiveUsersOfConfig derives the naive credential list from the sing-box config
// — the same inbound users PlanSingbox writes and the panel edits. One person on
// five inbounds is one entry here, keyed by name, so a rename follows and never
// splits into two accounts.
//
// blocked holds the names the lifecycle currently rejects (disabled, expired).
// sing-box enforces those through the managed route rule, which dest never sees,
// so they are dropped here instead.
func NaiveUsersOfConfig(cfg map[string]interface{}, blocked map[string]bool) []NaiveUser {
	rank := map[string]int{}
	for i, p := range naivePasswordProtocols {
		rank[p] = i + 1
	}
	type pick struct {
		password string
		rank     int
	}
	byName := map[string]pick{}
	for _, u := range users.ServerUsersOfConfig(cfg) {
		r, ok := rank[u.Protocol]
		if !ok || u.Name == "" || blocked[u.Name] {
			continue
		}
		if got, seen := byName[u.Name]; seen && got.rank <= r {
			continue
		}
		byName[u.Name] = pick{password: u.Credential, rank: r}
	}
	out := make([]NaiveUser, 0, len(byName))
	for name, p := range byName {
		out = append(out, NaiveUser{Name: name, Password: p.password})
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Name < out[j].Name })
	return out
}

// RenderNaiveUsers renders the basic_auth lines the Caddyfile imports into its
// forward_proxy block.
//
// An empty list is refused rather than rendered: forward_proxy with no
// credentials authenticates nobody, which means it relays for everybody.
func RenderNaiveUsers(list []NaiveUser) (string, error) {
	if len(list) == 0 {
		return "", errors.New("no naive users to render: dest with an empty credential list is an open proxy, so the previous list stays")
	}
	// Sorted here too, not only in NaiveUsersOfConfig: both are entry points, and
	// a list that arrives in a different order must not produce a different file
	// and a reload with it.
	sorted := append([]NaiveUser(nil), list...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Name < sorted[j].Name })

	var b strings.Builder
	b.WriteString("# Generated by RouteBox from the panel's users. Edits are overwritten.\n")
	for _, u := range sorted {
		if u.Name == "" || u.Password == "" {
			return "", fmt.Errorf("naive user %q has no name or no password", u.Name)
		}
		fmt.Fprintf(&b, "basic_auth %s %s\n", quote(u.Name), quote(u.Password))
	}
	return b.String(), nil
}

// naiveLockedUser is the account the list carries when the panel has no naive
// users left. The file cannot simply be empty — forward_proxy with no
// credentials authenticates nobody, which means it relays for everybody — so it
// carries one account instead, under a password nobody was ever given.
const naiveLockedUser = "routebox-no-users"

// lockedNaiveUsers is the list that locks naive: one account with a fresh random
// password. Random rather than a constant precisely because a constant in this
// file would be a credential anyone reading it could use.
func lockedNaiveUsers() ([]NaiveUser, error) {
	b := make([]byte, 32)
	if _, err := rand.Read(b); err != nil {
		return nil, fmt.Errorf("generate the lock password for naive: %w", err)
	}
	return []NaiveUser{{Name: naiveLockedUser, Password: hex.EncodeToString(b)}}, nil
}

// naiveListIsLocked reports whether the file already holds nothing but the
// locked account, so an install with no users does not re-lock (and reload dest) on
// every apply just because the lock password is random.
func naiveListIsLocked(body string) bool {
	var lines int
	for _, line := range strings.Split(body, "\n") {
		if strings.HasPrefix(strings.TrimSpace(line), "basic_auth ") {
			lines++
			if !strings.HasPrefix(strings.TrimSpace(line), "basic_auth "+naiveLockedUser+" ") {
				return false
			}
		}
	}
	return lines == 1
}

// SyncNaiveUsers writes the credential list dest checks naive against, and
// reports whether it changed. Unchanged means untouched: the caller reloads dest
// on a change, and a reload nobody needed is dropped connections for nothing.
//
// An empty list locks naive rather than opening it (see naiveLockedUser). A list
// that cannot be rendered at all leaves the file as it was — dest keeps
// authenticating against the previous list instead of failing to load.
func SyncNaiveUsers(path string, list []NaiveUser) (bool, error) {
	old, readErr := os.ReadFile(path)
	if len(list) == 0 {
		if readErr == nil && naiveListIsLocked(string(old)) {
			return false, nil
		}
		locked, err := lockedNaiveUsers()
		if err != nil {
			return false, err
		}
		list = locked
	}
	rendered, err := RenderNaiveUsers(list)
	if err != nil {
		return false, err
	}
	if readErr == nil && string(old) == rendered {
		return false, nil
	}
	if err := os.WriteFile(path, []byte(rendered), 0644); err != nil {
		return false, fmt.Errorf("write %s: %w", path, err)
	}
	return true, nil
}
