// Package bootstrap plans the configuration a fresh out-of-the-box install comes
// up with: the sing-box config here, the Caddyfile for dest next to it. Both are
// pure functions of Params — no filesystem, no network, no randomness. Secrets
// are generated by the caller and passed in, because a planner that makes its
// own cannot be checked against a fixed expectation.
package bootstrap

import (
	"fmt"
	"regexp"
	"sort"
	"strings"
)

// panelPathToken is what the panel's secret path is allowed to look like: see
// validate() for why it is stricter than the other paths.
var panelPathToken = regexp.MustCompile(`^/[A-Za-z0-9_-]+$`)

// Inbound tags of the planned config. Exported because the wrapper (and the
// Caddyfile planner) address these inbounds by tag.
const (
	TagVlessReality = "vless-reality-in"
	TagVlessGRPC    = "vless-grpc-in"
	TagTrojanWS     = "trojan-ws-in"
	TagMieru        = "mieru-in"
)

// Params is the whole input of the bootstrap planner — everything that differs
// between installations. Shared by PlanSingbox and the Caddyfile planner; this
// is the one place it is described.
type Params struct {
	Domain   string // own domain — Reality steals its own name (self-steal, ADR 0001)
	DestHost string // web server behind the front: stub site, panel, transport inbounds
	DestPort int
	StubRoot string // directory dest serves at the domain root — the stub site
	// NaiveUsers is the generated credential list the Caddyfile imports. It is a
	// separate file because it is the one part of dest's configuration that
	// changes after the install: every user added or removed in the panel
	// rewrites it, and nothing else (see SyncNaiveUsers).
	NaiveUsers string
	User       User
	Reality    Reality
	Ports      Ports
	Paths      Paths
	ACME       ACME
}

// User is the single account every inbound carries. PanelUser is derived from
// inbound.users[] by name, so one shared name yields one panel user rather than
// four, and the subscription does not fragment.
type User struct {
	Name     string
	UUID     string // vless
	Password string // trojan, mieru (and naive, rendered into the Caddyfile)
}

type Reality struct {
	PrivateKey string
	ShortID    string
}

type Ports struct {
	Front     int // external TCP — vless-reality, the front
	Mieru     int // external UDP — a different socket, no conflict with Front
	VlessGRPC int // loopback, behind dest
	TrojanWS  int // loopback, behind dest
	Panel     int // loopback, behind dest — the RouteBox panel itself
}

// Paths are the secret path-fork addresses of the transport inbounds behind dest.
// The Caddyfile planner routes exactly these to exactly those ports.
type Paths struct {
	VlessGRPC string // grpc service name
	TrojanWS  string // ws path, leading slash
	Panel     string // panel path, leading slash
}

// ACME is how dest gets the certificate the front borrows (ADR 0001): Caddy
// issues and renews it itself, so there is no certbot in the stack.
type ACME struct {
	Staging bool // point at the test CA instead, for dry runs against rate limits

	// Email is the ACME account contact. Optional — Let's Encrypt registers an
	// account without one — but then the notice that a renewal has been failing
	// for two weeks has nowhere to go, and the first sign is an expired
	// certificate on a server nobody was watching.
	Email string
}

// PlanSingbox builds the sing-box config a fresh install starts with: four
// inbounds, already wired, so the operator creates none of them by hand. The
// fifth protocol, naive, is served by dest and lives in the Caddyfile.
//
// Ports are float64 because that is what json.Unmarshal produces, and what
// everything downstream — the validator, the config manager — reads.
func PlanSingbox(p Params) (map[string]interface{}, error) {
	if err := p.validate(); err != nil {
		return nil, err
	}

	vlessUser := func() []interface{} {
		return []interface{}{map[string]interface{}{"name": p.User.Name, "uuid": p.User.UUID}}
	}
	passwordUser := func() []interface{} {
		return []interface{}{map[string]interface{}{"name": p.User.Name, "password": p.User.Password}}
	}

	realityIn := map[string]interface{}{
		"type": "vless", "tag": TagVlessReality,
		"listen": "::", "listen_port": float64(p.Ports.Front),
		// Vision needs a raw transport, which the front has — the path-forked
		// inbounds below cannot use it.
		"users": []interface{}{map[string]interface{}{
			"name": p.User.Name, "uuid": p.User.UUID, "flow": "xtls-rprx-vision",
		}},
		"tls": map[string]interface{}{
			"enabled":     true,
			"server_name": p.Domain,
			// No certificate of any kind: the handshake — and the real cert — come
			// from dest. That is the point of self-steal.
			"reality": map[string]interface{}{
				"enabled":     true,
				"handshake":   map[string]interface{}{"server": p.DestHost, "server_port": float64(p.DestPort)},
				"private_key": p.Reality.PrivateKey,
				"short_id":    []interface{}{p.Reality.ShortID},
			},
		},
	}

	// The two path-forked inbounds bind loopback and speak plaintext: dest
	// terminates TLS and forwards on the secret path. Binding loopback is also
	// how serverlinks recognises "behind the front" — no extra flag is stored.
	grpcIn := map[string]interface{}{
		"type": "vless", "tag": TagVlessGRPC,
		"listen": loopback, "listen_port": float64(p.Ports.VlessGRPC),
		"users":     vlessUser(),
		"transport": map[string]interface{}{"type": "grpc", "service_name": p.Paths.VlessGRPC},
	}
	trojanIn := map[string]interface{}{
		"type": "trojan", "tag": TagTrojanWS,
		"listen": loopback, "listen_port": float64(p.Ports.TrojanWS),
		"users":     passwordUser(),
		"transport": map[string]interface{}{"type": "ws", "path": p.Paths.TrojanWS},
	}

	// mieru has no TLS ClientHello, so the TCP front cannot fork it — it takes
	// 443/UDP directly.
	mieruIn := map[string]interface{}{
		"type": "mieru", "tag": TagMieru,
		"listen": "::", "listen_port": float64(p.Ports.Mieru),
		"transport": "UDP",
		"users":     passwordUser(),
	}

	return map[string]interface{}{
		"log":       map[string]interface{}{"level": "info", "timestamp": true},
		"inbounds":  []interface{}{realityIn, grpcIn, trojanIn, mieruIn},
		"outbounds": []interface{}{map[string]interface{}{"tag": "direct", "type": "direct"}},
		"route":     map[string]interface{}{"auto_detect_interface": true, "final": "direct"},
	}, nil
}

// loopback is where everything behind dest binds. ponytail: one address, not a
// Params field — an out-of-the-box install has dest and the inbounds on the same
// host by construction.
const loopback = "127.0.0.1"

func (p Params) validate() error {
	var missing []string
	for name, empty := range map[string]bool{
		"domain":              p.Domain == "",
		"dest host":           p.DestHost == "",
		"dest port":           p.DestPort <= 0,
		"user name":           p.User.Name == "",
		"user uuid":           p.User.UUID == "",
		"user password":       p.User.Password == "",
		"reality private key": p.Reality.PrivateKey == "",
		"reality short id":    p.Reality.ShortID == "",
		"front port":          p.Ports.Front <= 0,
		"mieru port":          p.Ports.Mieru <= 0,
		"vless grpc port":     p.Ports.VlessGRPC <= 0,
		"trojan ws port":      p.Ports.TrojanWS <= 0,
		"panel port":          p.Ports.Panel <= 0,
		"vless grpc path":     p.Paths.VlessGRPC == "",
		"trojan ws path":      p.Paths.TrojanWS == "",
		"panel path":          p.Paths.Panel == "",
		"stub root":           p.StubRoot == "",
		"naive users path":    p.NaiveUsers == "",
	} {
		if empty {
			missing = append(missing, name)
		}
	}
	if len(missing) > 0 {
		sort.Strings(missing)
		return fmt.Errorf("bootstrap params incomplete: %s", strings.Join(missing, ", "))
	}
	var bare []string
	for name, path := range map[string]string{"trojan ws path": p.Paths.TrojanWS, "panel path": p.Paths.Panel} {
		if !strings.HasPrefix(path, "/") {
			bare = append(bare, name)
		}
	}
	if len(bare) > 0 {
		sort.Strings(bare)
		return fmt.Errorf("bootstrap params: %s must start with /", strings.Join(bare, ", "))
	}
	// The panel path is also the gate cookie's value and the body of a substring
	// matcher, so it has to survive three grammars, not one. A token charset
	// satisfies all three and costs nothing: the value is generated, never typed.
	if !panelPathToken.MatchString(p.Paths.Panel) {
		return fmt.Errorf("bootstrap params: panel path must be / followed by letters, digits, - or _")
	}
	// These values land in the Caddyfile unquoted — as matchers and as a root —
	// where a character from caddyfileUnsafe is syntax rather than data.
	var unsafe []string
	for name, value := range map[string]string{
		"domain":           p.Domain,
		"dest host":        p.DestHost,
		"stub root":        p.StubRoot,
		"vless grpc path":  p.Paths.VlessGRPC,
		"trojan ws path":   p.Paths.TrojanWS,
		"panel path":       p.Paths.Panel,
		"naive users path": p.NaiveUsers,
	} {
		if strings.ContainsAny(value, caddyfileUnsafe) {
			unsafe = append(unsafe, name)
		}
	}
	if len(unsafe) > 0 {
		sort.Strings(unsafe)
		return fmt.Errorf("bootstrap params: %s must not contain whitespace, quotes, braces or backslashes", strings.Join(unsafe, ", "))
	}
	return nil
}
